export const allPosts = [
  {
    id: 1,
    userId: 1,
    desc: "Love for All, Hatred for none",
    image: "assets/post/post1.jpg",
    time: "5 days ago",
    like: 35,
    comment: 7,
  },
  {
    id: 2,
    userId: 2,
    desc: "That's great",
    image: "assets/post/post2.jpeg",
    time: "9 days ago",
    like: 65,
    comment: 21,
  },
  {
    id: 3,
    userId: 3,
    image: "assets/post/post3.jpg",
    time: "28 days ago",
    like: 102,
    comment: 67,
  },
  {
    id: 4,
    userId: 4,
    desc: "Hi, this is unblievable",
    image: "assets/post/post4.jpg",
    time: "23 days ago",
    like: 240,
    comment: 123,
  },
  {
    id: 5,
    userId: 5,
    desc: "Cool and Catchy",
    image: "assets/post/post5.jpg",
    time: "52 days ago",
    like: 655,
    comment: 92,
  },
  {
    id: 6,
    userId: 6,
    image: "assets/post/post1.jpg",
    time: "49 days ago",
    like: 865,
    comment: 234,
  },
  {
    id: 7,
    userId: 7,
    desc: "Every reaction their is an equal work opposite reaction",
    image: "assets/post/post2.jpeg",
    time: "76 days ago",
    like: 150,
    comment: 43,
  },
  {
    id: 8,
    userId: 8,
    image: "assets/post/post3.jpg",
    time: "9 days ago",
    like: 45,
    comment: 23,
  },
  {
    id: 9,
    userId: 9,
    desc: "nothing is better than anything",
    image: "assets/post/post4.jpg",
    time: "82 days ago",
    like: 56,
    comment: 8,
  },
  {
    id: 10,
    userId: 10,
    image: "assets/post/post5.jpg",
    time: "87 days ago",
    like: 45,
    comment: 14,
  },
];

export const allUsers = [
  {
    id: 1,
    picture: "/assets/person/person1.jpg",
    name: "Muhammad Nabeel",
  },
  {
    id: 2,
    picture: "/assets/person/person2.jpg",
    name: "Muhammad Hanzala",
  },
  {
    id: 3,
    picture: "/assets/person/person3.jpeg",
    name: "Aslam Ikram",
  },
  {
    id: 4,
    picture: "/assets/person/person4.jpeg",
    name: "Huzaifa Jamal",
  },
  {
    id: 5,
    picture: "/assets/person/person5.jpg",
    name: "David Mike",
  },
  {
    id: 6,
    picture: "/assets/person/person6.jpg",
    name: "Aisha Bilal",
  },
  {
    id: 7,
    picture: "/assets/person/person7.jpg",
    name: "Colin Joe",
  },
  {
    id: 8,
    picture: "/assets/person/person8.jpg",
    name: "Arshad Nadeem",
  },
  {
    id: 9,
    picture: "/assets/person/person9.jpg",
    name: "Shazaib Junaid",
  },
  {
    id: 10,
    picture: "/assets/person/person10.jpg",
    name: "Jaqueline Marsh",
  },
];
